/* Data for Idea Atlas (idea-atlas.html): philosophies and political ideologies.
 * start: year the tradition is usually dated from (negative = BCE).
 * kind: 'philosophy' | 'politics' | 'economics'.
 * history: [year, event]. thinkers: [name, dates, contribution, key work].
 * from: traditions it drew on. rivals: traditions it argued against or competed with.
 * Descriptions aim to be neutral: what supporters believe, and what critics say.
 */
(function (window) {
  'use strict';
  const I = [
    { id: 'confucianism', name: 'Confucianism', kind: 'philosophy', start: -500, era: '6th–5th century BCE', region: 'China, then East Asia',
      summary: 'An ethical and political tradition built on the teachings of Confucius. It holds that a good society comes from good character: people cultivate virtue through learning, ritual and respectful relationships, and rulers govern by moral example rather than by force.',
      ideas: ['Ren (humaneness) — caring, humane conduct toward others', 'Li (ritual propriety) — customs and manners that shape character', 'Filial piety — respect and duty toward parents and ancestors', 'Government by virtue: a ruler leads by moral example'],
      critics: 'Critics argue it reinforces rigid hierarchy (ruler over subject, father over son, husband over wife) and discourages dissent.',
      history: [[-479, 'Confucius dies; his students later compile the Analects'], [-136, 'Han Emperor Wu makes Confucianism the official state doctrine'], [605, 'Imperial civil-service exams based on the Confucian classics begin under the Sui dynasty'], [1905, 'The imperial examination system is abolished']],
      thinkers: [['Confucius (Kong Fuzi)', '551–479 BCE', 'Taught that moral cultivation and proper relationships create social harmony', 'Analects'], ['Mencius', 'c. 372–289 BCE', 'Argued that human nature is basically good', 'Mencius'], ['Xunzi', 'c. 310–235 BCE', 'Argued that human nature must be shaped by education and ritual', 'Xunzi'], ['Zhu Xi', '1130–1200', 'Created the Neo-Confucian synthesis that dominated East Asia for centuries', 'Commentaries on the Four Books']],
      from: ['daoism', 'buddhism'], rivals: [] },
    { id: 'daoism', name: 'Daoism (Taoism)', kind: 'philosophy', start: -400, era: '4th century BCE', region: 'China',
      summary: 'A tradition centred on the Dao, “the Way” — the natural flow underlying everything. Daoists value simplicity, spontaneity and living in harmony with nature, and they are suspicious of forced effort, rigid rules and ambition.',
      ideas: ['The Dao: the nameless source and pattern of all things', 'Wu wei — effortless action, not forcing things', 'Simplicity and naturalness (ziran)', 'Yin and yang: complementary opposites in balance'],
      critics: 'Confucian critics saw it as withdrawing from social and political responsibility.',
      history: [[-400, 'The Daodejing, attributed to Laozi, circulates in something like its present form'], [-300, 'Zhuangzi’s writings use humour and parables to explore freedom and change'], [142, 'Zhang Daoling founds the Way of the Celestial Masters, an early organised Daoist religion'], [1973, 'Silk manuscripts of the Daodejing are discovered at Mawangdui']],
      thinkers: [['Laozi', 'traditionally 6th century BCE', 'Legendary author of the Daodejing', 'Daodejing (Tao Te Ching)'], ['Zhuangzi', 'c. 369–286 BCE', 'Explored freedom, relativity of viewpoints and spontaneity through stories', 'Zhuangzi']],
      from: [], rivals: ['confucianism'] },
    { id: 'buddhism', name: 'Buddhist philosophy', kind: 'philosophy', start: -450, era: '5th century BCE', region: 'India, then all of Asia',
      summary: 'A tradition based on the teaching of Siddhartha Gautama, the Buddha. It analyses suffering and its causes and teaches a path — ethics, meditation and wisdom — to end it. Buddhist philosophers developed influential ideas about the self, change and emptiness.',
      ideas: ['The Four Noble Truths: suffering, its cause (craving), its end, and the path', 'Impermanence: everything changes', 'Non-self (anatta): there is no fixed, permanent self', 'The Middle Way between indulgence and harsh self-denial'],
      critics: 'Hindu and later Western critics questioned how rebirth and moral responsibility work without a lasting self.',
      history: [[-450, 'The Buddha teaches in northern India (dates are debated)'], [-250, 'Emperor Ashoka supports Buddhism and sends missions across Asia'], [150, 'Nagarjuna founds the Madhyamaka (“Middle Way”) school'], [1893, 'Buddhist teachers speak at the World’s Parliament of Religions in Chicago, raising Western interest']],
      thinkers: [['Siddhartha Gautama (the Buddha)', 'c. 5th century BCE', 'Taught the Four Noble Truths and the Eightfold Path', 'Teachings recorded in the Pali Canon'], ['Nagarjuna', 'c. 150–250 CE', 'Argued that all things are “empty” of independent existence', 'Mūlamadhyamakakārikā'], ['Vasubandhu', 'c. 4th–5th century CE', 'Co-founded the Yogācāra (mind-only) school', 'Twenty Verses']],
      from: [], rivals: [] },
    { id: 'platonism', name: 'Platonism', kind: 'philosophy', start: -387, era: '4th century BCE', region: 'Ancient Greece',
      summary: 'The philosophy of Plato, Socrates’ student. Plato argued that behind the changing world we see lie perfect, unchanging Forms (such as Justice or Beauty), which reason can grasp. His Republic describes a just city ruled by philosopher-kings.',
      ideas: ['Theory of Forms: true reality is ideal and unchanging', 'Knowledge comes through reason, not the senses', 'The soul has three parts: reason, spirit and appetite', 'Justice is each part of the soul and the city doing its proper job'],
      critics: 'Aristotle and later empiricists rejected separate Forms; modern critics such as Karl Popper saw the Republic as authoritarian.',
      history: [[-399, 'Socrates is executed in Athens'], [-387, 'Plato founds the Academy in Athens'], [250, 'Plotinus develops Neoplatonism in Rome'], [529, 'Emperor Justinian closes the pagan philosophy schools of Athens']],
      thinkers: [['Socrates', 'c. 470–399 BCE', 'Questioned everything through dialogue (the Socratic method)', 'Wrote nothing; known through Plato'], ['Plato', 'c. 428–348 BCE', 'Theory of Forms; ideal state', 'The Republic'], ['Plotinus', '204/5–270', 'Founded Neoplatonism: all reality flows from “the One”', 'Enneads']],
      from: [], rivals: [] },
    { id: 'aristotelianism', name: 'Aristotelianism & Thomism', kind: 'philosophy', start: -335, era: '4th century BCE', region: 'Ancient Greece, then Islamic world and Europe',
      summary: 'The philosophy of Aristotle, Plato’s student, who studied everything from logic and biology to ethics and politics. He grounded knowledge in observing the world. In the Middle Ages Thomas Aquinas combined Aristotle with Christian theology (Thomism).',
      ideas: ['Virtue ethics: a good life (eudaimonia) comes from developing good character', 'The golden mean: virtue lies between extremes', 'Humans are “political animals” who flourish in communities', 'Things have purposes (final causes)'],
      critics: 'The Scientific Revolution rejected Aristotle’s physics and his idea of purposes in nature.',
      history: [[-335, 'Aristotle founds the Lyceum in Athens'], [1150, 'Aristotle’s works return to Western Europe through Arabic translations and commentaries'], [1265, 'Thomas Aquinas begins the Summa Theologica'], [1958, 'Elizabeth Anscombe’s essay “Modern Moral Philosophy” revives virtue ethics']],
      thinkers: [['Aristotle', '384–322 BCE', 'Logic, virtue ethics, politics, biology', 'Nicomachean Ethics; Politics'], ['Thomas Aquinas', '1225–1274', 'Combined Aristotle with Christian theology; natural law', 'Summa Theologica'], ['Alasdair MacIntyre', '1929–2025', 'Revived Aristotelian virtue ethics', 'After Virtue (1981)']],
      from: ['platonism'], rivals: [] },
    { id: 'stoicism', name: 'Stoicism', kind: 'philosophy', start: -300, era: 'c. 300 BCE', region: 'Ancient Greece and Rome',
      summary: 'A practical philosophy founded in Athens by Zeno of Citium. Stoics teach that we cannot control events, only our judgements and actions, and that a good life means living by reason and virtue, calmly accepting what is outside our control.',
      ideas: ['The dichotomy of control: focus only on what is up to you', 'Virtue is the only true good', 'Live according to nature and reason', 'Cosmopolitanism: all humans are citizens of one world'],
      critics: 'Epicureans and later critics called Stoic calm unrealistic or emotionally cold.',
      history: [[-300, 'Zeno of Citium teaches at the Stoa Poikile (Painted Porch) in Athens'], [65, 'Seneca, the Roman statesman and Stoic writer, dies'], [180, 'Marcus Aurelius, the “philosopher emperor”, dies; his private notes become the Meditations'], [1955, 'Albert Ellis develops rational emotive behaviour therapy, quoting Epictetus: people are disturbed not by things but by their views of them']],
      thinkers: [['Zeno of Citium', 'c. 334–262 BCE', 'Founded the Stoic school', 'Republic (lost)'], ['Seneca', 'c. 4 BCE–65 CE', 'Practical letters on how to live', 'Letters to Lucilius'], ['Epictetus', 'c. 50–135 CE', 'Former slave who taught the dichotomy of control', 'Enchiridion (Handbook)'], ['Marcus Aurelius', '121–180', 'Roman emperor whose notes show Stoicism in practice', 'Meditations']],
      from: ['platonism'], rivals: ['epicureanism'] },
    { id: 'epicureanism', name: 'Epicureanism', kind: 'philosophy', start: -307, era: 'c. 307 BCE', region: 'Ancient Greece and Rome',
      summary: 'Founded by Epicurus, who taught that pleasure — understood as calm, freedom from pain and fear — is the goal of life. He recommended simple pleasures, friendship and understanding nature, and argued that death is nothing to fear.',
      ideas: ['The good life is ataraxia (peace of mind) and freedom from pain', 'Simple pleasures and friendship over luxury', 'Everything is made of atoms; gods do not interfere', '“Where death is, I am not”: death is nothing to fear'],
      critics: 'Stoics and Christians accused it of selfishness and atheism, often misreading it as indulgence.',
      history: [[-307, 'Epicurus opens his school, “the Garden”, in Athens'], [-55, 'Lucretius writes the poem De Rerum Natura'], [1417, 'Poggio Bracciolini rediscovers Lucretius’ poem, influencing the Renaissance'], [1789, 'Jeremy Bentham’s pleasure-based ethics echoes Epicurus']],
      thinkers: [['Epicurus', '341–270 BCE', 'Founded the school; pleasure as absence of pain', 'Letter to Menoeceus'], ['Lucretius', 'c. 99–55 BCE', 'Explained Epicurean atomism in poetry', 'De Rerum Natura (On the Nature of Things)']],
      from: [], rivals: ['stoicism'] },
    { id: 'islamic', name: 'Islamic philosophy (Falsafa)', kind: 'philosophy', start: 830, era: '9th century', region: 'Baghdad, Persia, Al-Andalus',
      summary: 'Philosophers in the Islamic world translated and extended Greek philosophy, especially Aristotle and the Neoplatonists, and debated how reason relates to revelation. Their commentaries preserved Greek learning and shaped medieval Europe.',
      ideas: ['Reason and revelation can agree', 'God as the Necessary Existent (Avicenna)', 'The virtuous city led by a philosopher-ruler (al-Farabi)', 'Debates on causation and the eternity of the world'],
      critics: 'Al-Ghazali argued that some philosophers’ claims contradicted Islamic faith; Ibn Rushd replied in defence of philosophy.',
      history: [[830, 'The House of Wisdom in Baghdad becomes a centre of translation'], [1027, 'Avicenna completes The Book of Healing'], [1095, 'Al-Ghazali writes The Incoherence of the Philosophers'], [1180, 'Ibn Rushd (Averroes) replies with The Incoherence of the Incoherence']],
      thinkers: [['Al-Kindi', 'c. 801–873', '“The philosopher of the Arabs”; introduced Greek philosophy', 'On First Philosophy'], ['Al-Farabi', 'c. 872–950', '“The Second Teacher” after Aristotle; political philosophy', 'The Virtuous City'], ['Avicenna (Ibn Sina)', '980–1037', 'Metaphysics and medicine', 'The Book of Healing; The Canon of Medicine'], ['Averroes (Ibn Rushd)', '1126–1198', 'Great commentator on Aristotle', 'The Incoherence of the Incoherence']],
      from: ['platonism', 'aristotelianism'], rivals: [] },
    { id: 'humanism', name: 'Renaissance humanism', kind: 'philosophy', start: 1350, era: '14th–16th century', region: 'Italy, then Europe',
      summary: 'A movement that revived the study of classical Greek and Roman texts and celebrated human dignity, education and achievement. Humanists promoted the “humanities” — grammar, rhetoric, history, poetry and moral philosophy.',
      ideas: ['Return to the classical sources (ad fontes)', 'The dignity and potential of human beings', 'Education in the humanities for active citizenship', 'Critical study of texts'],
      critics: 'Some religious critics feared it put humans above God; later thinkers found it elitist.',
      history: [[1341, 'Petrarch is crowned poet laureate in Rome'], [1440, 'Lorenzo Valla proves the Donation of Constantine is a forgery'], [1486, 'Pico della Mirandola writes the Oration on the Dignity of Man'], [1511, 'Erasmus publishes In Praise of Folly']],
      thinkers: [['Petrarch', '1304–1374', '“Father of humanism”; revived classical Latin', 'Letters'], ['Pico della Mirandola', '1463–1494', 'Humans can shape their own nature', 'Oration on the Dignity of Man'], ['Erasmus', '1466–1536', 'Christian humanist and satirist', 'In Praise of Folly']],
      from: ['platonism', 'aristotelianism', 'stoicism', 'islamic'], rivals: [] },
    { id: 'rationalism', name: 'Rationalism', kind: 'philosophy', start: 1637, era: '17th century', region: 'Europe',
      summary: 'The view that reason, not sense experience, is the main source of knowledge. Rationalists tried to build certain knowledge from first principles, inspired by mathematics.',
      ideas: ['Some knowledge is innate or known by reason alone', 'Certainty through deduction, as in geometry', '“I think, therefore I am” (Descartes)', 'Mind–body dualism (Descartes) or one substance (Spinoza)'],
      critics: 'Empiricists replied that all ideas come from experience.',
      history: [[1637, 'Descartes publishes the Discourse on the Method'], [1641, 'Descartes’ Meditations on First Philosophy'], [1677, 'Spinoza’s Ethics is published after his death'], [1714, 'Leibniz writes the Monadology']],
      thinkers: [['René Descartes', '1596–1650', '“Cogito, ergo sum”; methodical doubt', 'Meditations on First Philosophy'], ['Baruch Spinoza', '1632–1677', 'God and nature are one substance', 'Ethics'], ['Gottfried Leibniz', '1646–1716', 'Monads; co-invented calculus', 'Monadology']],
      from: ['platonism', 'aristotelianism', 'humanism'], rivals: ['empiricism'] },
    { id: 'empiricism', name: 'Empiricism', kind: 'philosophy', start: 1690, era: 'Late 17th century', region: 'Britain',
      summary: 'The view that knowledge comes from experience through the senses. Empiricists argued the mind starts as a “blank slate” and questioned claims that cannot be tested by experience.',
      ideas: ['The mind begins as a blank slate (tabula rasa)', 'All ideas come from sense experience', 'Scepticism about causation and induction (Hume)', 'Science advances by observation and experiment'],
      critics: 'Rationalists and Kant argued that experience alone cannot explain necessary truths like mathematics.',
      history: [[1620, 'Francis Bacon’s Novum Organum promotes experimental method'], [1690, 'Locke publishes An Essay Concerning Human Understanding'], [1710, 'Berkeley argues that to be is to be perceived'], [1739, 'Hume publishes A Treatise of Human Nature']],
      thinkers: [['John Locke', '1632–1704', 'Blank slate; also a founder of liberalism', 'An Essay Concerning Human Understanding'], ['George Berkeley', '1685–1753', 'Idealism: only minds and ideas exist', 'A Treatise Concerning the Principles of Human Knowledge'], ['David Hume', '1711–1776', 'Problem of induction; sceptic about causation', 'A Treatise of Human Nature']],
      from: ['aristotelianism'], rivals: ['rationalism'] },
    { id: 'kantianism', name: 'Kant & German idealism', kind: 'philosophy', start: 1781, era: 'Late 18th century', region: 'Germany',
      summary: 'Immanuel Kant combined rationalism and empiricism: we know the world only as our minds structure it. His ethics rests on duty and treating people as ends, never merely as means. Hegel and others developed “German idealism”, seeing history as the unfolding of reason.',
      ideas: ['The categorical imperative: act only on rules you could will for everyone', 'Treat people as ends in themselves, never merely as means', 'The mind shapes experience (space, time, causality)', 'Hegel: history progresses through conflict and resolution (dialectic)'],
      critics: 'Utilitarians say consequences matter more than rules; others found Hegel’s system obscure.',
      history: [[1781, 'Kant publishes the Critique of Pure Reason'], [1785, 'Kant’s Groundwork of the Metaphysics of Morals sets out the categorical imperative'], [1795, 'Kant’s Perpetual Peace proposes a federation of free states'], [1807, 'Hegel publishes the Phenomenology of Spirit']],
      thinkers: [['Immanuel Kant', '1724–1804', 'Categorical imperative; limits of reason', 'Critique of Pure Reason'], ['Johann Gottlieb Fichte', '1762–1814', 'Idealism; the self; German national education', 'Addresses to the German Nation'], ['G. W. F. Hegel', '1770–1831', 'Dialectic; history as the progress of freedom', 'Phenomenology of Spirit']],
      from: ['rationalism', 'empiricism'], rivals: ['utilitarianism'] },
    { id: 'utilitarianism', name: 'Utilitarianism', kind: 'philosophy', start: 1789, era: 'Late 18th century', region: 'Britain',
      summary: 'An ethical theory that judges actions by their results: the right action produces the greatest happiness for the greatest number. It shaped law reform, economics and modern debates on animal welfare and global poverty.',
      ideas: ['The greatest happiness of the greatest number', 'Actions are judged by their consequences', 'Everyone’s happiness counts equally', 'Mill: higher (intellectual) pleasures are better than lower ones'],
      critics: 'Critics say it can justify harming individuals or minorities if it increases total happiness.',
      history: [[1789, 'Bentham publishes An Introduction to the Principles of Morals and Legislation'], [1861, 'John Stuart Mill publishes Utilitarianism'], [1874, 'Henry Sidgwick’s The Methods of Ethics'], [1975, 'Peter Singer’s Animal Liberation applies utilitarian ideas to animals']],
      thinkers: [['Jeremy Bentham', '1748–1832', 'Founded modern utilitarianism; legal reform', 'An Introduction to the Principles of Morals and Legislation'], ['John Stuart Mill', '1806–1873', 'Refined utilitarianism; defended liberty', 'Utilitarianism'], ['Peter Singer', 'born 1946', 'Animal ethics and effective giving', 'Practical Ethics']],
      from: ['empiricism', 'epicureanism'], rivals: ['kantianism'] },
    { id: 'existentialism', name: 'Existentialism', kind: 'philosophy', start: 1843, era: '19th–20th century', region: 'Europe',
      summary: 'A philosophy focused on individual existence, freedom and choice. Existentialists argue that life has no pre-given meaning: we create meaning through our choices and must take responsibility for them, even in the face of anxiety and absurdity.',
      ideas: ['“Existence precedes essence” (Sartre)', 'Radical freedom and responsibility', 'Authenticity: live by your own choices, not by the crowd', 'The absurd: the clash between our search for meaning and a silent universe (Camus)'],
      critics: 'Critics call it pessimistic or too individualistic; Marxists said it ignored social conditions.',
      history: [[1843, 'Kierkegaard publishes Either/Or'], [1883, 'Nietzsche begins Thus Spoke Zarathustra'], [1942, 'Camus publishes The Myth of Sisyphus'], [1943, 'Sartre publishes Being and Nothingness']],
      thinkers: [['Søren Kierkegaard', '1813–1855', 'The individual, faith and anxiety', 'Either/Or; Fear and Trembling'], ['Friedrich Nietzsche', '1844–1900', '“God is dead”; create your own values', 'Thus Spoke Zarathustra'], ['Jean-Paul Sartre', '1905–1980', 'Existence precedes essence; radical freedom', 'Being and Nothingness'], ['Simone de Beauvoir', '1908–1986', 'Existentialist ethics and feminism', 'The Second Sex'], ['Albert Camus', '1913–1960', 'The absurd', 'The Myth of Sisyphus']],
      from: ['kantianism', 'phenomenology'], rivals: [] },
    { id: 'pragmatism', name: 'Pragmatism', kind: 'philosophy', start: 1878, era: 'Late 19th century', region: 'United States',
      summary: 'An American philosophy that judges ideas by their practical consequences. A belief is true if it works — if acting on it succeeds in experience. Pragmatists applied this to science, religion, education and democracy.',
      ideas: ['The meaning of an idea lies in its practical effects', 'Truth is what works in experience and inquiry', 'Knowledge is always open to revision (fallibilism)', 'Learning by doing (Dewey)'],
      critics: 'Critics say defining truth as “what works” can make truth relative or merely convenient.',
      history: [[1878, 'Peirce publishes “How to Make Our Ideas Clear”'], [1907, 'William James publishes Pragmatism, dedicated to J. S. Mill'], [1916, 'John Dewey publishes Democracy and Education'], [1979, 'Richard Rorty revives pragmatism with Philosophy and the Mirror of Nature']],
      thinkers: [['Charles Sanders Peirce', '1839–1914', 'Founded pragmatism; logic of inquiry', '“How to Make Our Ideas Clear”'], ['William James', '1842–1910', 'Popularised pragmatism; psychology', 'Pragmatism'], ['John Dewey', '1859–1952', 'Education and democracy', 'Democracy and Education']],
      from: ['empiricism', 'utilitarianism'], rivals: [] },
    { id: 'analytic', name: 'Analytic philosophy', kind: 'philosophy', start: 1879, era: 'Late 19th–20th century', region: 'Britain, Austria, United States',
      summary: 'A style of philosophy that stresses clear argument, logic and the analysis of language. Many analytic philosophers believed that philosophical problems come from misunderstanding how language works.',
      ideas: ['Clarity and rigorous logical argument', 'Analysing the meaning of language and concepts', 'Close links with science and mathematics', 'Logical positivism: meaningful claims must be verifiable (Vienna Circle)'],
      critics: 'Continental philosophers criticise it as narrow and technical, ignoring history and lived experience.',
      history: [[1879, 'Frege’s Begriffsschrift founds modern logic'], [1910, 'Russell and Whitehead publish Principia Mathematica'], [1921, 'Wittgenstein’s Tractatus Logico-Philosophicus'], [1953, 'Wittgenstein’s Philosophical Investigations published after his death']],
      thinkers: [['Gottlob Frege', '1848–1925', 'Modern logic; sense and reference', 'Begriffsschrift'], ['Bertrand Russell', '1872–1970', 'Logic, mathematics and public philosophy', 'Principia Mathematica'], ['Ludwig Wittgenstein', '1889–1951', 'Language and its limits', 'Tractatus Logico-Philosophicus']],
      from: ['empiricism'], rivals: ['postmodernism'] },
    { id: 'phenomenology', name: 'Phenomenology', kind: 'philosophy', start: 1900, era: 'Early 20th century', region: 'Germany and France',
      summary: 'The study of experience as it appears to us, from the first-person point of view. Phenomenologists set aside assumptions to describe how we actually experience objects, time, other people and our own bodies.',
      ideas: ['“To the things themselves!” — describe experience directly', 'Intentionality: consciousness is always of something', 'Being-in-the-world (Heidegger)', 'The lived body shapes perception (Merleau-Ponty)'],
      critics: 'Analytic critics find its language obscure and its method hard to test.',
      history: [[1900, 'Husserl publishes Logical Investigations'], [1927, 'Heidegger publishes Being and Time'], [1945, 'Merleau-Ponty publishes Phenomenology of Perception'], [1961, 'Levinas publishes Totality and Infinity']],
      thinkers: [['Edmund Husserl', '1859–1938', 'Founded phenomenology', 'Logical Investigations'], ['Martin Heidegger', '1889–1976', 'The question of Being', 'Being and Time'], ['Maurice Merleau-Ponty', '1908–1961', 'Embodiment and perception', 'Phenomenology of Perception']],
      from: ['kantianism', 'rationalism'], rivals: ['analytic'] },
    { id: 'criticaltheory', name: 'Critical theory (Frankfurt School)', kind: 'philosophy', start: 1923, era: '1920s', region: 'Germany, then United States',
      summary: 'A school of thinkers who combined Marx, Hegel and Freud to criticise modern society. They examined how culture, mass media and bureaucracy can keep people from recognising and changing unjust conditions.',
      ideas: ['Theory should help free people, not just describe society', 'The “culture industry” produces conformity', 'Instrumental reason can turn into domination', 'Habermas: democracy needs free, rational public discussion'],
      critics: 'Critics call it pessimistic, elitist about popular culture, or vague about solutions.',
      history: [[1923, 'The Institute for Social Research is founded in Frankfurt'], [1944, 'Horkheimer and Adorno write Dialectic of Enlightenment in exile'], [1964, 'Marcuse’s One-Dimensional Man influences the New Left'], [1981, 'Habermas publishes The Theory of Communicative Action']],
      thinkers: [['Max Horkheimer', '1895–1973', 'Defined “critical theory”', 'Dialectic of Enlightenment (with Adorno)'], ['Theodor Adorno', '1903–1969', 'The culture industry', 'Minima Moralia'], ['Herbert Marcuse', '1898–1979', 'Critique of consumer society', 'One-Dimensional Man'], ['Jürgen Habermas', 'born 1929', 'The public sphere; communicative action', 'The Theory of Communicative Action']],
      from: ['marxism', 'kantianism'], rivals: [] },
    { id: 'postmodernism', name: 'Postmodernism & post-structuralism', kind: 'philosophy', start: 1966, era: '1960s–1970s', region: 'France, then worldwide',
      summary: 'A group of approaches sceptical of grand explanations of history, fixed meanings and claims to neutral truth. They study how language, power and institutions shape what counts as knowledge and normal.',
      ideas: ['Scepticism toward “grand narratives” (Lyotard)', 'Knowledge and power are intertwined (Foucault)', 'Deconstruction: texts contain tensions that undo fixed meanings (Derrida)', 'Identities and categories are historically constructed'],
      critics: 'Critics say it leads to relativism, is needlessly obscure and makes it hard to defend truth or progress.',
      history: [[1966, 'Foucault publishes The Order of Things; Derrida speaks at Johns Hopkins'], [1967, 'Derrida publishes Of Grammatology'], [1975, 'Foucault publishes Discipline and Punish'], [1979, 'Lyotard publishes The Postmodern Condition']],
      thinkers: [['Michel Foucault', '1926–1984', 'Power, knowledge and institutions', 'Discipline and Punish'], ['Jacques Derrida', '1930–2004', 'Deconstruction', 'Of Grammatology'], ['Jean-François Lyotard', '1924–1998', 'Incredulity toward grand narratives', 'The Postmodern Condition']],
      from: ['phenomenology', 'existentialism'], rivals: ['analytic'] },
    { id: 'ubuntu', name: 'Ubuntu philosophy', kind: 'philosophy', start: 1960, era: 'Ancient oral roots; written from the 1960s', region: 'Southern and East Africa',
      summary: 'A southern African ethic expressed in the Nguni saying “umuntu ngumuntu ngabantu” — a person is a person through other people. It sees personhood as achieved through relationships, community, compassion and reconciliation.',
      ideas: ['“I am because we are”: identity comes through community', 'Humaneness, generosity and hospitality', 'Restorative rather than punishing justice', 'Consensus and shared responsibility'],
      critics: 'Some critics argue it can be used to pressure individuals to conform, or is too vague to guide law.',
      history: [[1969, 'John Mbiti writes “I am, because we are; and since we are, therefore I am”'], [1993, 'The interim South African Constitution refers to “a need for ubuntu”'], [1995, 'South Africa’s Truth and Reconciliation Commission is set up'], [1999, 'Desmond Tutu publishes No Future Without Forgiveness']],
      thinkers: [['John Mbiti', '1931–2019', 'Described African communal personhood', 'African Religions and Philosophy'], ['Desmond Tutu', '1931–2021', 'Ubuntu and reconciliation', 'No Future Without Forgiveness'], ['Mogobe Ramose', 'contemporary', 'Systematic philosophy of ubuntu', 'African Philosophy Through Ubuntu']],
      from: [], rivals: [] },

    // ---------------------------------------------------------------- politics & economics
    { id: 'liberalism', name: 'Liberalism', kind: 'politics', start: 1689, era: 'Late 17th century', region: 'Britain, France, United States',
      summary: 'A political tradition centred on individual liberty, equal rights and government by consent. Liberals support constitutional limits on power, the rule of law, free expression, religious tolerance and, usually, market economies.',
      ideas: ['Individual rights to life, liberty and property', 'Government by consent of the governed', 'Separation of powers and the rule of law', 'Freedom of speech and religious tolerance'],
      critics: 'Conservatives say it weakens tradition and community; socialists say formal rights hide economic inequality.',
      history: [[1689, 'Locke publishes Two Treatises of Government; English Bill of Rights'], [1748, 'Montesquieu’s The Spirit of the Laws proposes the separation of powers'], [1776, 'The US Declaration of Independence'], [1859, 'Mill publishes On Liberty'], [1971, 'Rawls publishes A Theory of Justice']],
      thinkers: [['John Locke', '1632–1704', 'Natural rights and consent', 'Two Treatises of Government'], ['Montesquieu', '1689–1755', 'Separation of powers', 'The Spirit of the Laws'], ['John Stuart Mill', '1806–1873', 'The harm principle', 'On Liberty'], ['John Rawls', '1921–2002', 'Justice as fairness', 'A Theory of Justice']],
      from: ['empiricism', 'humanism'], rivals: ['conservatism'] },
    { id: 'classical', name: 'Classical economics & free-market capitalism', kind: 'economics', start: 1776, era: 'Late 18th century', region: 'Britain',
      summary: 'The economic school that argued markets, competition and the division of labour create wealth, and that self-interest guided by prices can serve the common good — the “invisible hand”. It favoured free trade and limited government intervention.',
      ideas: ['The “invisible hand” of markets', 'Division of labour raises productivity', 'Free trade and comparative advantage', 'Limited state role in the economy'],
      critics: 'Socialists and Keynesians argue unregulated markets create inequality, crises and unemployment.',
      history: [[1776, 'Adam Smith publishes The Wealth of Nations'], [1817, 'Ricardo explains comparative advantage'], [1846, 'Britain repeals the Corn Laws, embracing free trade'], [1848, 'Mill publishes Principles of Political Economy']],
      thinkers: [['Adam Smith', '1723–1790', 'Invisible hand; division of labour', 'The Wealth of Nations'], ['David Ricardo', '1772–1823', 'Comparative advantage', 'On the Principles of Political Economy and Taxation'], ['Jean-Baptiste Say', '1767–1832', 'Say’s law of markets', 'A Treatise on Political Economy']],
      from: ['empiricism', 'liberalism'], rivals: ['marxism'] },
    { id: 'conservatism', name: 'Conservatism', kind: 'politics', start: 1790, era: '1790s', region: 'Britain, then worldwide',
      summary: 'A political outlook that values tradition, stable institutions and gradual change over rapid, radical reform. Modern conservatism began as a response to the French Revolution, arguing that inherited customs contain practical wisdom.',
      ideas: ['Respect for tradition and inherited institutions', 'Change should be gradual and organic', 'Scepticism of abstract, utopian plans', 'Importance of family, religion, community and property'],
      critics: 'Liberals and socialists argue it protects privilege and resists needed reforms.',
      history: [[1790, 'Burke publishes Reflections on the Revolution in France'], [1872, 'Disraeli promotes “one-nation” conservatism'], [1953, 'Russell Kirk publishes The Conservative Mind'], [1962, 'Oakeshott publishes Rationalism in Politics']],
      thinkers: [['Edmund Burke', '1729–1797', 'Father of modern conservatism', 'Reflections on the Revolution in France'], ['Benjamin Disraeli', '1804–1881', 'One-nation conservatism', 'Sybil (novel)'], ['Michael Oakeshott', '1901–1990', 'Critique of rationalist planning', 'Rationalism in Politics'], ['Roger Scruton', '1944–2020', 'Modern conservative philosophy', 'The Meaning of Conservatism']],
      from: ['aristotelianism', 'liberalism'], rivals: ['liberalism', 'socialism'] },
    { id: 'nationalism', name: 'Nationalism', kind: 'politics', start: 1789, era: 'Late 18th century', region: 'Europe, then worldwide',
      summary: 'The idea that people form nations with a shared language, culture or history, and that each nation should govern itself. It drove the unification of states, independence movements and anti-colonial struggles — and also wars and exclusion.',
      ideas: ['The nation as the basis of political community', 'National self-determination', 'Shared language, culture and history', 'Loyalty to the nation-state'],
      critics: 'Critics warn it can become exclusionary, xenophobic or aggressive; Marxists favour international class solidarity.',
      history: [[1789, 'The French Revolution declares sovereignty rests with the nation'], [1808, 'Fichte delivers the Addresses to the German Nation'], [1861, 'The Kingdom of Italy is proclaimed'], [1918, 'Woodrow Wilson’s Fourteen Points promote self-determination']],
      thinkers: [['Johann Gottfried Herder', '1744–1803', 'Each people has its own spirit and language', 'Ideas on the Philosophy of the History of Mankind'], ['Giuseppe Mazzini', '1805–1872', 'Italian unification; democratic nationalism', 'The Duties of Man'], ['Johann Gottlieb Fichte', '1762–1814', 'Cultural-national education', 'Addresses to the German Nation']],
      from: ['kantianism', 'liberalism'], rivals: ['marxism'] },
    { id: 'socialism', name: 'Socialism', kind: 'politics', start: 1820, era: '1820s–1830s', region: 'Britain and France, then worldwide',
      summary: 'A family of ideas that the economy should be owned or controlled collectively so that wealth is shared more equally. Early “utopian” socialists built model communities; later socialists sought change through unions, parties or revolution.',
      ideas: ['Social or collective ownership of key resources', 'Production for need rather than profit', 'Greater economic equality', 'Cooperation and solidarity among workers'],
      critics: 'Free-market critics argue it removes incentives, concentrates power in the state and fails to allocate resources efficiently.',
      history: [[1813, 'Robert Owen publishes A New View of Society'], [1825, 'Owen founds the New Harmony community in the United States'], [1864, 'The First International is founded in London'], [1899, 'Bernstein argues for gradual, democratic socialism']],
      thinkers: [['Robert Owen', '1771–1858', 'Cooperative communities', 'A New View of Society'], ['Henri de Saint-Simon', '1760–1825', 'Society run by productive experts', 'The New Christianity'], ['Charles Fourier', '1772–1837', 'Cooperative “phalanxes”', 'The Theory of the Four Movements']],
      from: ['liberalism', 'utilitarianism'], rivals: ['classical'] },
    { id: 'anarchism', name: 'Anarchism', kind: 'politics', start: 1840, era: '1840s', region: 'France and Russia, then worldwide',
      summary: 'The belief that the state and other forced hierarchies are unnecessary and harmful, and that society should be organised through voluntary cooperation. Anarchists split from Marxists over whether a workers’ state was needed.',
      ideas: ['Abolition of the state and coercive authority', 'Voluntary cooperation and mutual aid', 'Direct action and self-management', 'Means must match ends: no dictatorship to reach freedom'],
      critics: 'Critics argue a stateless society cannot provide security or would collapse into rule by the strongest.',
      history: [[1840, 'Proudhon asks What Is Property? and calls himself an anarchist'], [1872, 'Anarchists led by Bakunin are expelled from the First International'], [1902, 'Kropotkin publishes Mutual Aid'], [1936, 'Anarchists collectivise parts of Catalonia during the Spanish Civil War']],
      thinkers: [['Pierre-Joseph Proudhon', '1809–1865', '“Property is theft”; mutualism', 'What Is Property?'], ['Mikhail Bakunin', '1814–1876', 'Collectivist anarchism', 'Statism and Anarchy'], ['Peter Kropotkin', '1842–1921', 'Cooperation in nature and society', 'Mutual Aid'], ['Emma Goldman', '1869–1940', 'Anarchism and women’s freedom', 'Anarchism and Other Essays']],
      from: ['socialism', 'liberalism'], rivals: ['leninism', 'marxism'] },
    { id: 'marxism', name: 'Marxism', kind: 'politics', start: 1848, era: '1848', region: 'Germany and Britain, then worldwide',
      summary: 'The theory of Karl Marx and Friedrich Engels that history is driven by class struggle and that capitalism exploits workers. They predicted that workers would overthrow capitalism and build a classless, communist society.',
      ideas: ['History is a history of class struggle', 'Historical materialism: economics shapes society and ideas', 'Capitalism exploits workers’ labour (surplus value)', 'A classless society without private ownership of the means of production'],
      critics: 'Critics point out that its predictions of revolution in industrial nations did not come true and that states built on it became authoritarian.',
      history: [[1848, 'Marx and Engels publish The Communist Manifesto'], [1867, 'Volume 1 of Capital is published'], [1889, 'The Second International unites socialist parties'], [1929, 'Gramsci begins his Prison Notebooks']],
      thinkers: [['Karl Marx', '1818–1883', 'Historical materialism; critique of capitalism', 'Capital; The Communist Manifesto'], ['Friedrich Engels', '1820–1895', 'Co-founder; wrote on working-class conditions', 'The Condition of the Working Class in England'], ['Rosa Luxemburg', '1871–1919', 'Revolutionary democracy', 'Reform or Revolution?'], ['Antonio Gramsci', '1891–1937', 'Cultural hegemony', 'Prison Notebooks']],
      from: ['kantianism', 'socialism', 'classical'], rivals: ['classical', 'anarchism'] },
    { id: 'leninism', name: 'Marxism–Leninism (Communism)', kind: 'politics', start: 1917, era: '1917', region: 'Russia, then USSR, China, Cuba, Vietnam and others',
      summary: 'Lenin’s version of Marxism, in which a disciplined vanguard party leads a revolution and rules through a one-party state on the way to communism. It became the official ideology of the Soviet Union and other communist states.',
      ideas: ['A vanguard party leads the working class', 'Dictatorship of the proletariat after revolution', 'State planning of the economy', 'Anti-imperialism'],
      critics: 'Historians document one-party dictatorship, political repression and famines under these regimes; anarchists and democratic socialists rejected the vanguard model.',
      history: [[1902, 'Lenin publishes What Is to Be Done?'], [1917, 'The Bolsheviks take power in the October Revolution'], [1949, 'Mao Zedong proclaims the People’s Republic of China'], [1991, 'The Soviet Union dissolves']],
      thinkers: [['Vladimir Lenin', '1870–1924', 'Vanguard party; led the October Revolution', 'The State and Revolution'], ['Leon Trotsky', '1879–1940', 'Permanent revolution; later opposed Stalin', 'The Revolution Betrayed'], ['Mao Zedong', '1893–1976', 'Peasant-based revolution in China', 'On Contradiction']],
      from: ['marxism'], rivals: ['anarchism', 'socialdemocracy', 'liberalism'] },
    { id: 'socialdemocracy', name: 'Social democracy', kind: 'politics', start: 1899, era: 'Late 19th–20th century', region: 'Germany and Scandinavia, then Europe',
      summary: 'A reformist tradition that seeks social justice within a democratic, market economy — through welfare states, public services, workers’ rights and progressive taxes — rather than by revolution.',
      ideas: ['Reform through elections, not revolution', 'Welfare state and universal public services', 'A regulated mixed economy', 'Strong unions and workers’ rights'],
      critics: 'Free-market critics cite high taxes and debt; revolutionary socialists say it only manages capitalism.',
      history: [[1899, 'Bernstein publishes Evolutionary Socialism'], [1932, 'Swedish Social Democrats begin 44 years in government'], [1948, 'Britain’s National Health Service is founded'], [1959, 'Germany’s SPD accepts the market economy in the Godesberg Programme']],
      thinkers: [['Eduard Bernstein', '1850–1932', 'Revisionism: socialism through reform', 'Evolutionary Socialism'], ['Hjalmar Branting', '1860–1925', 'Led Sweden’s first social democratic government', '—'], ['Clement Attlee', '1883–1967', 'UK prime minister who built the welfare state', '—'], ['Anthony Crosland', '1918–1977', 'Modern reformist socialism', 'The Future of Socialism']],
      from: ['marxism', 'socialism', 'liberalism', 'keynesianism'], rivals: ['leninism', 'neoliberalism'] },
    { id: 'feminism', name: 'Feminism', kind: 'politics', start: 1792, era: 'Late 18th century', region: 'Worldwide',
      summary: 'Movements and theories that seek equal rights and opportunities for women and challenge discrimination based on sex and gender. Historians often describe waves: votes and legal rights, then workplace and family equality, then diversity and intersectionality.',
      ideas: ['Equal political, legal and economic rights for women', 'Challenging gender roles and stereotypes', '“The personal is political”', 'Intersectionality: race, class and gender interact'],
      critics: 'Critics from different sides question particular claims, strategies or its relation to tradition; feminists themselves debate many issues.',
      history: [[1792, 'Wollstonecraft publishes A Vindication of the Rights of Woman'], [1848, 'The Seneca Falls Convention demands women’s rights in the US'], [1893, 'New Zealand becomes the first self-governing country to give women the vote'], [1949, 'Beauvoir publishes The Second Sex'], [1979, 'The UN adopts CEDAW, the women’s rights convention']],
      thinkers: [['Mary Wollstonecraft', '1759–1797', 'Education and reason for women', 'A Vindication of the Rights of Woman'], ['Simone de Beauvoir', '1908–1986', '“One is not born, but becomes, a woman”', 'The Second Sex'], ['Betty Friedan', '1921–2006', 'Second-wave feminism', 'The Feminine Mystique'], ['bell hooks', '1952–2021', 'Race, class and gender', 'Ain’t I a Woman?']],
      from: ['liberalism', 'existentialism', 'marxism'], rivals: [] },
    { id: 'fascism', name: 'Fascism', kind: 'politics', start: 1919, era: '1919', region: 'Italy, Germany and elsewhere in Europe',
      summary: 'A far-right, authoritarian nationalist ideology that emerged after World War I. Fascist regimes built one-party dictatorships around a leader cult, glorified violence and war, and crushed opposition. Nazism added extreme racism, leading to the Holocaust.',
      ideas: ['Extreme nationalism and national rebirth', 'Dictatorship and a single leader', 'Rejection of liberal democracy and communism', 'Glorification of violence and militarism'],
      critics: 'Fascism was defeated in World War II and is widely condemned for its dictatorships, wars of aggression and genocide.',
      history: [[1919, 'Mussolini founds the Fasci di Combattimento in Milan'], [1922, 'The March on Rome brings Mussolini to power'], [1933, 'Hitler becomes Chancellor of Germany'], [1945, 'Fascist Italy and Nazi Germany are defeated in World War II']],
      thinkers: [['Benito Mussolini', '1883–1945', 'Founder and dictator of Fascist Italy', 'The Doctrine of Fascism (with Gentile)'], ['Giovanni Gentile', '1875–1944', 'Philosopher of Italian Fascism', 'The Doctrine of Fascism'], ['Adolf Hitler', '1889–1945', 'Nazi dictator responsible for the Holocaust', 'Mein Kampf']],
      from: ['nationalism'], rivals: ['liberalism', 'marxism', 'leninism'] },
    { id: 'keynesianism', name: 'Keynesian economics', kind: 'economics', start: 1936, era: '1930s', region: 'Britain, then worldwide',
      summary: 'John Maynard Keynes argued that markets do not always fix themselves: in a slump, total demand can stay too low, causing mass unemployment. Governments should spend and borrow in downturns to support demand.',
      ideas: ['Aggregate demand drives output and jobs', 'Government spending can counter recessions', 'Active fiscal and monetary policy', 'Markets can get stuck with high unemployment'],
      critics: 'Monetarists and free-market economists blamed Keynesian policies for inflation and large government debt in the 1970s.',
      history: [[1936, 'Keynes publishes The General Theory of Employment, Interest and Money'], [1944, 'The Bretton Woods conference shapes the post-war economy'], [1970, 'Stagflation challenges Keynesian policy'], [2009, 'Large stimulus programmes respond to the global financial crisis']],
      thinkers: [['John Maynard Keynes', '1883–1946', 'Aggregate demand; government stabilisation', 'The General Theory'], ['Joan Robinson', '1903–1983', 'Developed Keynesian and post-Keynesian theory', 'The Accumulation of Capital'], ['Paul Samuelson', '1915–2009', 'Combined Keynes with neoclassical economics', 'Economics (textbook)']],
      from: ['classical', 'liberalism'], rivals: ['neoliberalism'] },
    { id: 'christiandemocracy', name: 'Christian democracy', kind: 'politics', start: 1891, era: 'Late 19th–20th century', region: 'Europe and Latin America',
      summary: 'A centre-right tradition that applies Christian social teaching to democratic politics. It combines support for markets and family with social welfare, cooperation between workers and employers, and European unity.',
      ideas: ['Human dignity and the common good', 'Subsidiarity: decide at the most local level possible', 'A social market economy', 'Cooperation between classes instead of class struggle'],
      critics: 'Secular critics object to religion in politics; free-market critics find it too interventionist.',
      history: [[1891, 'Pope Leo XIII issues Rerum Novarum on the rights of workers'], [1919, 'Luigi Sturzo founds the Italian People’s Party'], [1945, 'Germany’s CDU is founded; Adenauer leads it from 1946'], [1950, 'The Schuman Declaration launches European integration']],
      thinkers: [['Pope Leo XIII', '1810–1903', 'Catholic social teaching', 'Rerum Novarum'], ['Luigi Sturzo', '1871–1959', 'Founder of Christian democratic politics in Italy', '—'], ['Konrad Adenauer', '1876–1967', 'First Chancellor of West Germany', '—'], ['Robert Schuman', '1886–1963', 'A founding father of the European Union', 'Schuman Declaration']],
      from: ['aristotelianism', 'conservatism'], rivals: ['leninism'] },
    { id: 'panafricanism', name: 'Pan-Africanism', kind: 'politics', start: 1900, era: '1900', region: 'Africa and the African diaspora',
      summary: 'A movement for the unity, solidarity and self-determination of African peoples on the continent and in the diaspora. It inspired anti-colonial independence struggles and continental organisations.',
      ideas: ['Unity and solidarity of African peoples worldwide', 'Independence from colonial rule', 'Pride in African history and culture', 'Continental cooperation and integration'],
      critics: 'Critics note tensions between continental unity and national sovereignty, and that some leaders became authoritarian.',
      history: [[1900, 'Henry Sylvester Williams organises the first Pan-African Conference in London'], [1945, 'The Fifth Pan-African Congress meets in Manchester'], [1957, 'Ghana becomes independent under Kwame Nkrumah'], [1963, 'The Organisation of African Unity is founded'], [2002, 'The African Union replaces the OAU']],
      thinkers: [['W. E. B. Du Bois', '1868–1963', '“The problem of the colour line”', 'The Souls of Black Folk'], ['Marcus Garvey', '1887–1940', 'Black pride and self-reliance', 'Universal Negro Improvement Association'], ['Kwame Nkrumah', '1909–1972', 'Ghana’s independence leader; African unity', 'Africa Must Unite'], ['Julius Nyerere', '1922–1999', 'Ujamaa (African socialism) in Tanzania', 'Ujamaa: Essays on Socialism']],
      from: ['nationalism', 'socialism', 'ubuntu'], rivals: [] },
    { id: 'libertarianism', name: 'Libertarianism', kind: 'politics', start: 1944, era: 'Mid-20th century', region: 'United States and Austria',
      summary: 'A philosophy that puts individual liberty first and wants the smallest possible state — often limited to protecting people, property and contracts. Libertarians oppose most regulation, redistribution and restrictions on personal choices.',
      ideas: ['Self-ownership and individual rights', 'A minimal “night-watchman” state', 'Free markets and voluntary exchange', 'Personal freedom in private life'],
      critics: 'Critics argue it ignores inequality, public goods and the needs of people who cannot compete in markets.',
      history: [[1944, 'Hayek publishes The Road to Serfdom'], [1957, 'Ayn Rand publishes Atlas Shrugged'], [1971, 'The US Libertarian Party is founded'], [1974, 'Nozick publishes Anarchy, State, and Utopia']],
      thinkers: [['Friedrich Hayek', '1899–1992', 'Planning threatens freedom; knowledge in markets', 'The Road to Serfdom'], ['Milton Friedman', '1912–2006', 'Free markets and monetarism', 'Capitalism and Freedom'], ['Robert Nozick', '1938–2002', 'Minimal state; entitlement theory', 'Anarchy, State, and Utopia'], ['Ayn Rand', '1905–1982', 'Objectivism; rational self-interest', 'Atlas Shrugged']],
      from: ['liberalism', 'classical'], rivals: ['socialism'] },
    { id: 'neoliberalism', name: 'Neoliberalism', kind: 'economics', start: 1947, era: '1947; in government from 1979', region: 'Worldwide',
      summary: 'A policy approach favouring free markets, privatisation, deregulation, free trade and lower taxes, with the state creating conditions for competition. It shaped governments and international institutions from the 1980s.',
      ideas: ['Markets allocate resources better than governments', 'Privatisation and deregulation', 'Free trade and capital flows', 'Controlling inflation through monetary policy'],
      critics: 'Critics link it to rising inequality, weakened public services and financial crises; supporters credit it with growth and lower inflation.',
      history: [[1947, 'Hayek founds the Mont Pelerin Society'], [1979, 'Margaret Thatcher becomes UK prime minister'], [1981, 'Ronald Reagan becomes US president'], [1989, 'The “Washington Consensus” policy list is named']],
      thinkers: [['Friedrich Hayek', '1899–1992', 'Founded the Mont Pelerin Society', 'The Constitution of Liberty'], ['Milton Friedman', '1912–2006', 'Monetarism', 'Free to Choose'], ['Margaret Thatcher', '1925–2013', 'Privatisation and market reforms in the UK', '—']],
      from: ['classical', 'libertarianism'], rivals: ['keynesianism', 'socialdemocracy'] },
    { id: 'environmentalism', name: 'Environmentalism & green politics', kind: 'politics', start: 1962, era: '1960s', region: 'Worldwide',
      summary: 'A movement to protect nature, reduce pollution and live within the planet’s limits. Green politics adds ideas of sustainability, social justice, non-violence and grassroots democracy, and today centres on climate change.',
      ideas: ['Ecological sustainability for future generations', 'Protecting biodiversity and nature’s value', 'Limits to growth on a finite planet', 'Climate action and climate justice'],
      critics: 'Critics argue some green policies are costly, slow economic growth or burden poorer people and countries.',
      history: [[1949, 'Aldo Leopold’s A Sand County Almanac proposes a “land ethic”'], [1962, 'Rachel Carson publishes Silent Spring'], [1970, 'The first Earth Day'], [1977, 'Wangari Maathai founds the Green Belt Movement in Kenya'], [2015, 'The Paris Agreement on climate change']],
      thinkers: [['Rachel Carson', '1907–1964', 'Exposed the dangers of pesticides', 'Silent Spring'], ['Aldo Leopold', '1887–1948', 'The land ethic', 'A Sand County Almanac'], ['Arne Næss', '1912–2009', 'Deep ecology', 'Ecology, Community and Lifestyle'], ['Wangari Maathai', '1940–2011', 'Tree planting, democracy and women’s rights; Nobel Peace Prize 2004', 'Unbowed']],
      from: ['anarchism', 'feminism'], rivals: [] }
  ];
  window.IDEAS = I;
})(window);
