/* Posts each tool's tutorial video to YouTube, with a description that says
 * what the tool does and links to it on migabuilder.com.
 *
 *   node scripts/tutorial-videos/youtube-publish.mjs preview [tool…]   # write the posts to videos/youtube-posts.md, no upload
 *   node scripts/tutorial-videos/youtube-publish.mjs auth              # one-time: get YT_REFRESH_TOKEN
 *   node scripts/tutorial-videos/youtube-publish.mjs upload [tool…]    # upload the videos not posted yet
 *
 * Upload needs YT_CLIENT_ID, YT_CLIENT_SECRET and YT_REFRESH_TOKEN in the
 * environment (see README.md). Options: --privacy=public|unlisted|private
 * (default public), --limit=N (default 6: the daily API quota allows about
 * that many uploads), --playlist=ID (also add each video to this playlist).
 * Posted videos are recorded in videos/youtube.json, so running again only
 * uploads what is left. */
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { fileURLToPath } from 'node:url';
import { SCENARIOS } from './scenarios.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const SITE = 'https://migabuilder.com/';
const MANIFEST = JSON.parse(fs.readFileSync(path.join(ROOT, 'videos/manifest.json'), 'utf8'));
const STATE_FILE = path.join(ROOT, 'videos/youtube.json');
const SCOPE = 'https://www.googleapis.com/auth/youtube';

const args = process.argv.slice(2);
const command = args[0];
const opts = Object.fromEntries(args.filter(a => a.startsWith('--')).map(a => a.slice(2).split('=')));
const only = args.slice(1).filter(a => !a.startsWith('--')).map(a => a.endsWith('.html') ? a : a + '.html');

const loadState = () => fs.existsSync(STATE_FILE) ? JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')) : {};
const saveState = s => fs.writeFileSync(STATE_FILE, JSON.stringify(s, null, 1) + '\n');

// YouTube rejects < and > in titles and descriptions.
const clean = s => s.replace(/[<>]/g, '');

function buildPost(file) {
  const m = MANIFEST[file];
  const sc = SCENARIOS[file] || {};
  const url = SITE + file;
  const [intro, ...steps] = m.transcript;
  const title = clean(`${m.title}: ${sc.subtitle || 'free online tool'} | MigaBuilder`).slice(0, 100);
  const description = clean([
    `${m.title} — ${sc.subtitle || ''}`.replace(/ — $/, ''),
    '',
    `▶ Try ${m.title} free, no sign-up: ${url}`,
    '',
    intro,
    '',
    'In this video:',
    ...steps.map(s => '• ' + s),
    '',
    `More free tools: ${SITE}`,
    '',
    `#MigaBuilder #${m.title.replace(/[^A-Za-z0-9]/g, '')} #FreeTools`
  ].join('\n')).slice(0, 4900);
  const tags = ['MigaBuilder', m.title, 'free online tool', 'tutorial', 'how to',
    ...(sc.subtitle || '').toLowerCase().split(/[^a-z0-9-]+/).filter(w => w.length > 3)];
  const uniq = [...new Set(tags)];
  while (uniq.join(',').length > 450) uniq.pop();
  return { file, url, title, description, tags: uniq, video: path.join(ROOT, m.video), poster: path.join(ROOT, m.poster) };
}

function selectedTools() {
  const files = only.length ? only : Object.keys(MANIFEST);
  const unknown = files.filter(f => !MANIFEST[f]);
  if (unknown.length) throw new Error('No video for: ' + unknown.join(', '));
  return files;
}

async function preview() {
  const out = selectedTools().map(f => {
    const p = buildPost(f);
    return `## ${p.title}\n\nVideo: \`${path.relative(ROOT, p.video)}\`  \nTags: ${p.tags.join(', ')}\n\n\`\`\`\n${p.description}\n\`\`\`\n`;
  });
  const dest = path.join(ROOT, 'videos/youtube-posts.md');
  fs.writeFileSync(dest, `# YouTube posts\n\nGenerated by \`scripts/tutorial-videos/youtube-publish.mjs preview\`.\n\n${out.join('\n')}`);
  console.log(`Wrote ${out.length} posts to ${path.relative(ROOT, dest)}`);
}

function env(name) {
  const v = process.env[name];
  if (!v) throw new Error(`${name} is not set. See scripts/tutorial-videos/README.md, "Posting to YouTube".`);
  return v;
}

async function googleJson(res) {
  const body = await res.json().catch(() => null);
  if (!res.ok) {
    const err = new Error(body?.error?.message || body?.error_description || `HTTP ${res.status}`);
    err.reason = body?.error?.errors?.[0]?.reason;
    throw err;
  }
  return body;
}

async function tokenRequest(params) {
  return googleJson(await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ client_id: env('YT_CLIENT_ID'), client_secret: env('YT_CLIENT_SECRET'), ...params })
  }));
}

// Loopback OAuth flow for a "Desktop app" OAuth client: open the printed URL,
// sign in with the Google account that owns the channel, and the refresh
// token is printed here.
async function auth() {
  const clientId = env('YT_CLIENT_ID');
  env('YT_CLIENT_SECRET');
  const server = http.createServer();
  await new Promise(r => server.listen(0, '127.0.0.1', r));
  const redirect = `http://127.0.0.1:${server.address().port}`;
  const url = 'https://accounts.google.com/o/oauth2/v2/auth?' + new URLSearchParams({
    client_id: clientId, redirect_uri: redirect, response_type: 'code',
    scope: SCOPE, access_type: 'offline', prompt: 'consent'
  });
  console.log('Open this link, sign in with the account that owns your channel, and allow access:\n\n' + url + '\n');
  const code = await new Promise((resolve, reject) => server.on('request', (req, res) => {
    const q = new URL(req.url, redirect).searchParams;
    res.end(q.get('code') ? 'Done. You can close this tab.' : 'Sign-in failed: ' + q.get('error'));
    server.close();
    q.get('code') ? resolve(q.get('code')) : reject(new Error(q.get('error')));
  }));
  const tok = await tokenRequest({ code, redirect_uri: redirect, grant_type: 'authorization_code' });
  console.log('\nYT_REFRESH_TOKEN=' + tok.refresh_token + '\n\nKeep this secret. Add it as a GitHub Actions secret to post from GitHub.');
}

async function uploadOne(token, post, privacy) {
  const size = fs.statSync(post.video).size;
  const init = await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status', {
    method: 'POST',
    headers: {
      Authorization: 'Bearer ' + token,
      'Content-Type': 'application/json; charset=UTF-8',
      'X-Upload-Content-Type': 'video/mp4',
      'X-Upload-Content-Length': String(size)
    },
    body: JSON.stringify({
      snippet: { title: post.title, description: post.description, tags: post.tags, categoryId: '27' /* Education */, defaultLanguage: 'en' },
      status: { privacyStatus: privacy, selfDeclaredMadeForKids: false }
    })
  });
  if (!init.ok) await googleJson(init);
  const video = await googleJson(await fetch(init.headers.get('location'), {
    method: 'PUT',
    headers: { 'Content-Type': 'video/mp4' },
    body: fs.readFileSync(post.video)
  }));
  // Custom thumbnails need a verified channel; the video is fine without one.
  try {
    await googleJson(await fetch(`https://www.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=${video.id}`, {
      method: 'POST',
      headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'image/jpeg' },
      body: fs.readFileSync(post.poster)
    }));
  } catch (e) { console.warn(`  thumbnail not set: ${e.message}`); }
  if (opts.playlist) {
    await googleJson(await fetch('https://www.googleapis.com/youtube/v3/playlistItems?part=snippet', {
      method: 'POST',
      headers: { Authorization: 'Bearer ' + token, 'Content-Type': 'application/json' },
      body: JSON.stringify({ snippet: { playlistId: opts.playlist, resourceId: { kind: 'youtube#video', videoId: video.id } } })
    }));
  }
  return video;
}

async function upload() {
  const privacy = opts.privacy || 'public';
  const limit = Number(opts.limit || 6);
  const state = loadState();
  const todo = selectedTools().filter(f => !state[f]).slice(0, limit);
  if (!todo.length) { console.log('Nothing to upload: every selected video is already on YouTube.'); return; }
  const { access_token } = await tokenRequest({ refresh_token: env('YT_REFRESH_TOKEN'), grant_type: 'refresh_token' });
  for (const file of todo) {
    const post = buildPost(file);
    console.log(`Uploading ${file} …`);
    try {
      const v = await uploadOne(access_token, post, privacy);
      state[file] = { id: v.id, url: 'https://youtu.be/' + v.id, privacy: v.status?.privacyStatus || privacy, uploadedAt: new Date().toISOString() };
      saveState(state);
      console.log(`  ${state[file].url}`);
    } catch (e) {
      if (['quotaExceeded', 'uploadLimitExceeded', 'rateLimitExceeded'].includes(e.reason)) {
        console.log(`  YouTube's daily limit reached (${e.reason}). Run again tomorrow to continue.`);
        break;
      }
      throw e;
    }
  }
  const left = Object.keys(MANIFEST).filter(f => !state[f]).length;
  console.log(`${Object.keys(state).length} posted, ${left} left.`);
}

const commands = { preview, auth, upload };
if (!commands[command]) {
  console.log('Usage: youtube-publish.mjs preview|auth|upload [tool…] [--privacy=public] [--limit=6] [--playlist=ID]');
  process.exit(1);
}
commands[command]().catch(e => { console.error(e.message); process.exit(1); });
